In [1]:
import numpy as np

a = [1, 2, 3, 4]

b = np.asarray(a)

print(a)
print(b)

print(type(a))
print(type(b))

print(b.shape)
print(b.ndim)

[1, 2, 3, 4]
[1 2 3 4]
<class 'list'>
<class 'numpy.ndarray'>
(4,)
1


In [2]:
a = [
    [1, 2, 3],
    [4, 5, 6]
]

b = np.asarray(a)

print(b)
print(type(b))
print(b.shape)
print(b.ndim)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
2


In [3]:
a = [
    [1, 2, 3],
    [4, 5, 6]
]

b = np.asarray(a)

print(b.sum())
print(b.sum(axis=0))
print(b.sum(axis=1))

21
[5 7 9]
[ 6 15]


In [ ]:
# argsort вернуть отсортированные ИНДЕКСЫ по значению
vectors = np.asarray([ 
	[0,1,0,1,0],
	[1,0,0,1,0],
	[0,1,0,1,0],
	[1,0,0,0,1],
	[0,1,0,0,0]
])

vectors.argsort()

array([[0, 2, 4, 1, 3],
       [1, 2, 4, 0, 3],
       [0, 2, 4, 1, 3],
       [1, 2, 3, 0, 4],
       [0, 2, 3, 4, 1]], dtype=int64)

In [8]:
simple = np.asarray([1,9,5,3,11])
simple.argsort()

array([0, 3, 2, 1, 4], dtype=int64)