In [28]:
# Начальная секция где мы делаем инициализацию, более подробно
import numpy as np
import matplotlib.pyplot as plt


rng = np.random.default_rng(seed=42)
m = 10  # number of instances
X = 6 * rng.random((m, 1)) - 3
y = 0.5 * X**2 + X + 2 + rng.standard_normal((m, 1))

ran_3_1 = rng.random((3, 1))
print("3 строки, 1 колонка, без изменений:",ran_3_1, "\n") # uniform distribution чисел от 0 до 1
print("поэлементное умножение на 6:",6 * ran_3_1, "\n")
print("поэлементное вычитание",ran_3_1 - 3)



3 строки, 1 колонка, без изменений: [[0.75808774]
 [0.35452597]
 [0.97069802]] 

поэлементное умножение на 6: [[4.54852644]
 [2.12715581]
 [5.82418815]] 

поэлементное вычитание [[-2.24191226]
 [-2.64547403]
 [-2.02930198]]


In [ ]:
# rng.random разбор

# 2 строки × 3 колонки
print(rng.random((2, 3)), "\n") 
# 3 строки × 3 колонки
print(rng.random((3, 3)), "\n")
# 2 строки × 4 колонки
print(rng.random((3, 4)), "\n") 
# 5 строки × 1 колонки
print(rng.random((5, 1)), "\n") # То есть это уже близко к нашему примеру где 200 строк на колонку

[[0.20236336 0.30595662 0.57921957]
 [0.17677278 0.85661428 0.75851953]] 

[[0.71946296 0.43209304 0.62730884]
 [0.58409797 0.6498466  0.08444432]
 [0.4158074  0.04161417 0.49399082]] 

[[0.32986121 0.14452419 0.10340297 0.58764457]
 [0.17059297 0.92512012 0.58106114 0.3468698 ]
 [0.59091549 0.02280387 0.95855921 0.48230344]] 

[[0.78273523]
 [0.08273   ]
 [0.48665833]
 [0.49070699]
 [0.93782645]] 



In [59]:
# rng.standard_normal разбор


# нормальное распределение, где:
# среднее = 0
# стандартное отклонение = 1
# значения чаще всего находятся около 0
# отрицательные и положительные значения возможны

print(rng.standard_normal((2, 3)))

[[ 0.64393879 -2.0501721  -0.0487184 ]
 [-0.84323027 -1.21881306 -0.87815237]]


In [98]:
# Разбор строки y = 0.5 * X**2 + X + 2 + rng.standard_normal((m, 1))
rng = np.random.default_rng(seed=42)

example_x = rng.random((1,2))
std_n = rng.standard_normal((1, 2))
result = 0.5 * example_x**2 + example_x + 2 + std_n
print("result:",result,"\n")

# X**2 поэлементно каждый возводится во вторую степень
x_2_ex = example_x
print("ориг",x_2_ex)
print("возвели", x_2_ex**2,"\n")

# После возведения мы перемножаем на 0.5
x_2_ex_af =0.5 * x_2_ex**2
print("Возведенное перемножаем на 0.5",x_2_ex_af,"\n") 

# Снова складываем, прибавляем себя же, но ориг и каждый складываем 2
x_2_ex_sum_it = x_2_ex_af + x_2_ex + 2
print(x_2_ex_sum_it, "\n")

# Делаем норм рандом распределение
print("std_n:", std_n, "\n")
# И складываем это
print("финальный",x_2_ex_sum_it + std_n)

result: [[3.82391123 3.4757503 ]] 

ориг [[0.77395605 0.43887844]]
возвели [[0.59900797 0.19261428]] 

Возведенное перемножаем на 0.5 [[0.29950398 0.09630714]] 

[[3.07346003 2.53518558]] 

std_n: [[0.7504512  0.94056472]] 

финальный [[3.82391123 3.4757503 ]]
