In [5]:
import numpy as np
from sklearn.preprocessing import add_dummy_feature

# Допустим, у нас есть 3 объекта и один признак X
X = np.array([
    [2],
    [4],
    [6]
])

y = np.array([
    [5],
    [9],
    [13]
])

print("X:")
print(X)

# ─────────────────────────────
# 1. add_dummy_feature
# ─────────────────────────────
# Добавляет слева колонку из единиц.
#
# Было:
# [2]
# [4]
# [6]
#
# Стало:
# [1  2]
# [1  4]
# [1  6]

X_b = add_dummy_feature(X)

print("\nX_b:")
print(X_b)

print("\nX_b.T:")
print(X_b.T)


# ─────────────────────────────
# 2. X_b.T @ X_b
# ─────────────────────────────
#
# .T = транспонировать
# @  = умножение матриц

A = X_b.T @ X_b

print("\nX_b.T @ X_b:")
print(A)


# ─────────────────────────────
# 3. np.linalg.inv()
# ─────────────────────────────
# inv() находит ОБРАТНУЮ матрицу.
#
# То есть:
#
# A @ A_inverse = единичная матрица

A_inv = np.linalg.inv(A)

print("\nОбратная матрица:")
print(A_inv)


# ─────────────────────────────
# 4. X_b.T @ y
# ─────────────────────────────

B = X_b.T @ y

print("\nX_b.T @ y:")
print(B)


# ─────────────────────────────
# 5. Всё вместе
# ─────────────────────────────

theta = A_inv @ B

print("\ntheta:")
print(theta)

X:
[[2]
 [4]
 [6]]

X_b:
[[1. 2.]
 [1. 4.]
 [1. 6.]]

X_b.T:
[[1. 1. 1.]
 [2. 4. 6.]]

X_b.T @ X_b:
[[ 3. 12.]
 [12. 56.]]

Обратная матрица:
[[ 2.33333333 -0.5       ]
 [-0.5         0.125     ]]

X_b.T @ y:
[[ 27.]
 [124.]]

theta:
[[1.]
 [2.]]


In [ ]:
# После X_b.T @ X_b , у нас есть
# [ a  b ]
# [ c  d ]
a = 3
b = 12
c = 12
d = 56

# Считаем determinant
det = a*d - b*c
det = 3*56 - 12*12
det = 168 - 144
det = 24

# Меняем элементы по формуле обратной матрицы
# [ a  b ]
# [ c  d ]
# Обратная 
# 1/det × [ d  -b ]
#           [ -c  a ]
# 1/24 × [ 56  -12 ]
#          [ -12   3 ]
# 56 / 24 = 2.33333333
# -12 / 24 = -0.5
# 3 / 24 = 0.125

In [ ]:
#  формула обратной матрицы
# [ a  b ]⁻¹      1          [  d  -b ]
# [ c  d ]   =  ────────  ×  [ -c   a ]
#                ad - bc